// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.34.1
// source: proto/scannerv1/scanner.proto

package scannerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{0}
}

type ScanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilesFound    int32 `protobuf:"varint,1,opt,name=files_found,json=filesFound,proto3" json:"files_found,omitempty"`
	FilesImported int32 `protobuf:"varint,2,opt,name=files_imported,json=filesImported,proto3" json:"files_imported,omitempty"`
	FilesSkipped  int32 `protobuf:"varint,3,opt,name=files_skipped,json=filesSkipped,proto3" json:"files_skipped,omitempty"`
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetFilesFound() int32 {
	if x != nil {
		return x.FilesFound
	}
	return 0
}

func (x *ScanResponse) GetFilesImported() int32 {
	if x != nil {
		return x.FilesImported
	}
	return 0
}

func (x *ScanResponse) GetFilesSkipped() int32 {
	if x != nil {
		return x.FilesSkipped
	}
	return 0
}

type ScanLibraryRootsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScanLibraryRootsRequest) Reset() {
	*x = ScanLibraryRootsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanLibraryRootsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanLibraryRootsRequest) ProtoMessage() {}

func (x *ScanLibraryRootsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanLibraryRootsRequest.ProtoReflect.Descriptor instead.
func (*ScanLibraryRootsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{2}
}

type ScanLibraryRootsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilesFound    int32 `protobuf:"varint,1,opt,name=files_found,json=filesFound,proto3" json:"files_found,omitempty"`
	FilesImported int32 `protobuf:"varint,2,opt,name=files_imported,json=filesImported,proto3" json:"files_imported,omitempty"`
	FilesSkipped  int32 `protobuf:"varint,3,opt,name=files_skipped,json=filesSkipped,proto3" json:"files_skipped,omitempty"`
}

func (x *ScanLibraryRootsResponse) Reset() {
	*x = ScanLibraryRootsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanLibraryRootsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanLibraryRootsResponse) ProtoMessage() {}

func (x *ScanLibraryRootsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanLibraryRootsResponse.ProtoReflect.Descriptor instead.
func (*ScanLibraryRootsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *ScanLibraryRootsResponse) GetFilesFound() int32 {
	if x != nil {
		return x.FilesFound
	}
	return 0
}

func (x *ScanLibraryRootsResponse) GetFilesImported() int32 {
	if x != nil {
		return x.FilesImported
	}
	return 0
}

func (x *ScanLibraryRootsResponse) GetFilesSkipped() int32 {
	if x != nil {
		return x.FilesSkipped
	}
	return 0
}

type GetStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{4}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalImported  int32  `protobuf:"varint,1,opt,name=total_imported,json=totalImported,proto3" json:"total_imported,omitempty"`
	WatchDirs      int32  `protobuf:"varint,2,opt,name=watch_dirs,json=watchDirs,proto3" json:"watch_dirs,omitempty"`
	LastScanAt     int64  `protobuf:"varint,3,opt,name=last_scan_at,json=lastScanAt,proto3" json:"last_scan_at,omitempty"`
	LastScanStatus string `protobuf:"bytes,4,opt,name=last_scan_status,json=lastScanStatus,proto3" json:"last_scan_status,omitempty"`
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatsResponse) GetTotalImported() int32 {
	if x != nil {
		return x.TotalImported
	}
	return 0
}

func (x *GetStatsResponse) GetWatchDirs() int32 {
	if x != nil {
		return x.WatchDirs
	}
	return 0
}

func (x *GetStatsResponse) GetLastScanAt() int64 {
	if x != nil {
		return x.LastScanAt
	}
	return 0
}

func (x *GetStatsResponse) GetLastScanStatus() string {
	if x != nil {
		return x.LastScanStatus
	}
	return ""
}

type AddWatchDirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path        string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MediaType   string `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`       // "movie", "tv", "both"
	LibraryPath string `protobuf:"bytes,3,opt,name=library_path,json=libraryPath,proto3" json:"library_path,omitempty"` // where to move organized files
}

func (x *AddWatchDirRequest) Reset() {
	*x = AddWatchDirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddWatchDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWatchDirRequest) ProtoMessage() {}

func (x *AddWatchDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWatchDirRequest.ProtoReflect.Descriptor instead.
func (*AddWatchDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{6}
}

func (x *AddWatchDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddWatchDirRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *AddWatchDirRequest) GetLibraryPath() string {
	if x != nil {
		return x.LibraryPath
	}
	return ""
}

type AddWatchDirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddWatchDirResponse) Reset() {
	*x = AddWatchDirResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddWatchDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWatchDirResponse) ProtoMessage() {}

func (x *AddWatchDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWatchDirResponse.ProtoReflect.Descriptor instead.
func (*AddWatchDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{7}
}

func (x *AddWatchDirResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveWatchDirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveWatchDirRequest) Reset() {
	*x = RemoveWatchDirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveWatchDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWatchDirRequest) ProtoMessage() {}

func (x *RemoveWatchDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWatchDirRequest.ProtoReflect.Descriptor instead.
func (*RemoveWatchDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveWatchDirRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveWatchDirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveWatchDirResponse) Reset() {
	*x = RemoveWatchDirResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveWatchDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWatchDirResponse) ProtoMessage() {}

func (x *RemoveWatchDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWatchDirResponse.ProtoReflect.Descriptor instead.
func (*RemoveWatchDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{9}
}

type ListWatchDirsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListWatchDirsRequest) Reset() {
	*x = ListWatchDirsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWatchDirsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchDirsRequest) ProtoMessage() {}

func (x *ListWatchDirsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchDirsRequest.ProtoReflect.Descriptor instead.
func (*ListWatchDirsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{10}
}

type ListWatchDirsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dirs []*WatchDir `protobuf:"bytes,1,rep,name=dirs,proto3" json:"dirs,omitempty"`
}

func (x *ListWatchDirsResponse) Reset() {
	*x = ListWatchDirsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWatchDirsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchDirsResponse) ProtoMessage() {}

func (x *ListWatchDirsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchDirsResponse.ProtoReflect.Descriptor instead.
func (*ListWatchDirsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{11}
}

func (x *ListWatchDirsResponse) GetDirs() []*WatchDir {
	if x != nil {
		return x.Dirs
	}
	return nil
}

type WatchDir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path        string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	MediaType   string `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	LibraryPath string `protobuf:"bytes,4,opt,name=library_path,json=libraryPath,proto3" json:"library_path,omitempty"`
	Enabled     bool   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt   string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *WatchDir) Reset() {
	*x = WatchDir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchDir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDir) ProtoMessage() {}

func (x *WatchDir) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDir.ProtoReflect.Descriptor instead.
func (*WatchDir) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{12}
}

func (x *WatchDir) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WatchDir) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WatchDir) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *WatchDir) GetLibraryPath() string {
	if x != nil {
		return x.LibraryPath
	}
	return ""
}

func (x *WatchDir) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WatchDir) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListImportedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	MediaType string `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
}

func (x *ListImportedRequest) Reset() {
	*x = ListImportedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListImportedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImportedRequest) ProtoMessage() {}

func (x *ListImportedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImportedRequest.ProtoReflect.Descriptor instead.
func (*ListImportedRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{13}
}

func (x *ListImportedRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListImportedRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListImportedRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type ListImportedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files    []*ImportedFile `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Total    int32           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page     int32           `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32           `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListImportedResponse) Reset() {
	*x = ListImportedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListImportedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImportedResponse) ProtoMessage() {}

func (x *ListImportedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImportedResponse.ProtoReflect.Descriptor instead.
func (*ListImportedResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{14}
}

func (x *ListImportedResponse) GetFiles() []*ImportedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListImportedResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListImportedResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListImportedResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ImportedFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalPath    string `protobuf:"bytes,2,opt,name=original_path,json=originalPath,proto3" json:"original_path,omitempty"`
	DestinationPath string `protobuf:"bytes,3,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	FileName        string `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MediaType       string `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Title           string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Year            int32  `protobuf:"varint,7,opt,name=year,proto3" json:"year,omitempty"`
	SeasonNumber    int32  `protobuf:"varint,8,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeNumber   int32  `protobuf:"varint,9,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	Quality         string `protobuf:"bytes,10,opt,name=quality,proto3" json:"quality,omitempty"`
	TmdbId          int32  `protobuf:"varint,11,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	ImportedAt      string `protobuf:"bytes,12,opt,name=imported_at,json=importedAt,proto3" json:"imported_at,omitempty"`
	Status          string `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ImportedFile) Reset() {
	*x = ImportedFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scannerv1_scanner_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportedFile) ProtoMessage() {}

func (x *ImportedFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportedFile.ProtoReflect.Descriptor instead.
func (*ImportedFile) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{15}
}

func (x *ImportedFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImportedFile) GetOriginalPath() string {
	if x != nil {
		return x.OriginalPath
	}
	return ""
}

func (x *ImportedFile) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *ImportedFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ImportedFile) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ImportedFile) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImportedFile) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ImportedFile) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *ImportedFile) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *ImportedFile) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *ImportedFile) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *ImportedFile) GetImportedAt() string {
	if x != nil {
		return x.ImportedAt
	}
	return ""
}

func (x *ImportedFile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_scannerv1_scanner_proto protoreflect.FileDescriptor

var file_proto_scannerv1_scanner_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x76,
	0x31, 0x2f, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x6d, 0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x7b, 0x0a, 0x0c, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x5f, 0x66, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x46, 0x6f,
	0x75, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x5f, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x5f, 0x73, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x53, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x22,
	0x19, 0x0a, 0x17, 0x53, 0x63, 0x61, 0x6e, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x52, 0x6f,
	0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x87, 0x01, 0x0a, 0x18, 0x53,
	0x63, 0x61, 0x6e, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x52, 0x6f, 0x6f, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x5f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x5f, 0x73, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x53, 0x6b, 0x69,
	0x70, 0x70, 0x65, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa4, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x64, 0x69, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x77, 0x61, 0x74, 0x63, 0x68, 0x44, 0x69,
	0x72, 0x73, 0x12, 0x20, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x63, 0x61, 0x6e, 0x5f,
	0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x63,
	0x61, 0x6e, 0x41, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x63, 0x61,
	0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x6c, 0x61, 0x73, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x6a,
	0x0a, 0x12, 0x41, 0x64, 0x64, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x69, 0x62, 0x72, 0x61,
	0x72, 0x79, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x50, 0x61, 0x74, 0x68, 0x22, 0x25, 0x0a, 0x13, 0x41, 0x64,
	0x64, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x27, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x44, 0x69, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x15,
	0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x69, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x69,
	0x72, 0x52, 0x04, 0x64, 0x69, 0x72, 0x73, 0x22, 0xa9, 0x01, 0x0a, 0x08, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x44, 0x69, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x69, 0x62, 0x72, 0x61,
	0x72, 0x79, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0x65, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x14, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x22, 0x8c, 0x03, 0x0a, 0x0c, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x25,
	0x0a, 0x0e, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12,
	0x17, 0x0a, 0x07, 0x74, 0x6d, 0x64, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x74, 0x6d, 0x64, 0x62, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x32, 0xb3, 0x05, 0x0a, 0x0e, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x04, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x1f, 0x2e, 0x6d,
	0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x6d, 0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x6d, 0x0a, 0x10, 0x53, 0x63, 0x61, 0x6e, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x52, 0x6f,
	0x6f, 0x74, 0x73, 0x12, 0x2b, 0x2e, 0x6d, 0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x4c, 0x69, 0x62,
	0x72, 0x61, 0x72, 0x79, 0x52, 0x6f, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2c, 0x2e, 0x6d, 0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x79, 0x52, 0x6f, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x23, 0x2e, 0x6d, 0x75, 0x78,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x6d, 0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x44, 0x69, 0x72, 0x12, 0x26, 0x2e, 0x6d, 0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73,
	0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6d,
	0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x64, 0x64, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x44, 0x69, 0x72, 0x12, 0x29, 0x2e, 0x6d, 0x75, 0x78, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6d, 0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64,
	0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x69, 0x72, 0x73, 0x12,
	0x28, 0x2e, 0x6d, 0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x69,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6d, 0x75, 0x78, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x44, 0x69, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x12, 0x27, 0x2e, 0x6d, 0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73,
	0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x6d, 0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x75, 0x78, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2d, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x76,
	0x31, 0x3b, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_scannerv1_scanner_proto_rawDescOnce sync.Once
	file_proto_scannerv1_scanner_proto_rawDescData = file_proto_scannerv1_scanner_proto_rawDesc
)

func file_proto_scannerv1_scanner_proto_rawDescGZIP() []byte {
	file_proto_scannerv1_scanner_proto_rawDescOnce.Do(func() {
		file_proto_scannerv1_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_scannerv1_scanner_proto_rawDescData)
	})
	return file_proto_scannerv1_scanner_proto_rawDescData
}

var file_proto_scannerv1_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_scannerv1_scanner_proto_goTypes = []interface{}{
	(*ScanRequest)(nil),              // 0: muxcore.scanner.v1.ScanRequest
	(*ScanResponse)(nil),             // 1: muxcore.scanner.v1.ScanResponse
	(*ScanLibraryRootsRequest)(nil),  // 2: muxcore.scanner.v1.ScanLibraryRootsRequest
	(*ScanLibraryRootsResponse)(nil), // 3: muxcore.scanner.v1.ScanLibraryRootsResponse
	(*GetStatsRequest)(nil),          // 4: muxcore.scanner.v1.GetStatsRequest
	(*GetStatsResponse)(nil),         // 5: muxcore.scanner.v1.GetStatsResponse
	(*AddWatchDirRequest)(nil),       // 6: muxcore.scanner.v1.AddWatchDirRequest
	(*AddWatchDirResponse)(nil),      // 7: muxcore.scanner.v1.AddWatchDirResponse
	(*RemoveWatchDirRequest)(nil),    // 8: muxcore.scanner.v1.RemoveWatchDirRequest
	(*RemoveWatchDirResponse)(nil),   // 9: muxcore.scanner.v1.RemoveWatchDirResponse
	(*ListWatchDirsRequest)(nil),     // 10: muxcore.scanner.v1.ListWatchDirsRequest
	(*ListWatchDirsResponse)(nil),    // 11: muxcore.scanner.v1.ListWatchDirsResponse
	(*WatchDir)(nil),                 // 12: muxcore.scanner.v1.WatchDir
	(*ListImportedRequest)(nil),      // 13: muxcore.scanner.v1.ListImportedRequest
	(*ListImportedResponse)(nil),     // 14: muxcore.scanner.v1.ListImportedResponse
	(*ImportedFile)(nil),             // 15: muxcore.scanner.v1.ImportedFile
}
var file_proto_scannerv1_scanner_proto_depIdxs = []int32{
	12, // 0: muxcore.scanner.v1.ListWatchDirsResponse.dirs:type_name -> muxcore.scanner.v1.WatchDir
	15, // 1: muxcore.scanner.v1.ListImportedResponse.files:type_name -> muxcore.scanner.v1.ImportedFile
	0,  // 2: muxcore.scanner.v1.ScannerService.Scan:input_type -> muxcore.scanner.v1.ScanRequest
	2,  // 3: muxcore.scanner.v1.ScannerService.ScanLibraryRoots:input_type -> muxcore.scanner.v1.ScanLibraryRootsRequest
	4,  // 4: muxcore.scanner.v1.ScannerService.GetStats:input_type -> muxcore.scanner.v1.GetStatsRequest
	6,  // 5: muxcore.scanner.v1.ScannerService.AddWatchDir:input_type -> muxcore.scanner.v1.AddWatchDirRequest
	8,  // 6: muxcore.scanner.v1.ScannerService.RemoveWatchDir:input_type -> muxcore.scanner.v1.RemoveWatchDirRequest
	10, // 7: muxcore.scanner.v1.ScannerService.ListWatchDirs:input_type -> muxcore.scanner.v1.ListWatchDirsRequest
	13, // 8: muxcore.scanner.v1.ScannerService.ListImported:input_type -> muxcore.scanner.v1.ListImportedRequest
	1,  // 9: muxcore.scanner.v1.ScannerService.Scan:output_type -> muxcore.scanner.v1.ScanResponse
	3,  // 10: muxcore.scanner.v1.ScannerService.ScanLibraryRoots:output_type -> muxcore.scanner.v1.ScanLibraryRootsResponse
	5,  // 11: muxcore.scanner.v1.ScannerService.GetStats:output_type -> muxcore.scanner.v1.GetStatsResponse
	7,  // 12: muxcore.scanner.v1.ScannerService.AddWatchDir:output_type -> muxcore.scanner.v1.AddWatchDirResponse
	9,  // 13: muxcore.scanner.v1.ScannerService.RemoveWatchDir:output_type -> muxcore.scanner.v1.RemoveWatchDirResponse
	11, // 14: muxcore.scanner.v1.ScannerService.ListWatchDirs:output_type -> muxcore.scanner.v1.ListWatchDirsResponse
	14, // 15: muxcore.scanner.v1.ScannerService.ListImported:output_type -> muxcore.scanner.v1.ListImportedResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_scannerv1_scanner_proto_init() }
func file_proto_scannerv1_scanner_proto_init() {
	if File_proto_scannerv1_scanner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_scannerv1_scanner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanLibraryRootsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanLibraryRootsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddWatchDirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddWatchDirResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveWatchDirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveWatchDirResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWatchDirsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWatchDirsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchDir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListImportedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListImportedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scannerv1_scanner_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportedFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_scannerv1_scanner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scannerv1_scanner_proto_goTypes,
		DependencyIndexes: file_proto_scannerv1_scanner_proto_depIdxs,
		MessageInfos:      file_proto_scannerv1_scanner_proto_msgTypes,
	}.Build()
	File_proto_scannerv1_scanner_proto = out.File
	file_proto_scannerv1_scanner_proto_rawDesc = nil
	file_proto_scannerv1_scanner_proto_goTypes = nil
	file_proto_scannerv1_scanner_proto_depIdxs = nil
}
