// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: proto/scannerv1/scanner.proto

package scannerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{0}
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesFound    int32                  `protobuf:"varint,1,opt,name=files_found,json=filesFound,proto3" json:"files_found,omitempty"`
	FilesImported int32                  `protobuf:"varint,2,opt,name=files_imported,json=filesImported,proto3" json:"files_imported,omitempty"`
	FilesSkipped  int32                  `protobuf:"varint,3,opt,name=files_skipped,json=filesSkipped,proto3" json:"files_skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetFilesFound() int32 {
	if x != nil {
		return x.FilesFound
	}
	return 0
}

func (x *ScanResponse) GetFilesImported() int32 {
	if x != nil {
		return x.FilesImported
	}
	return 0
}

func (x *ScanResponse) GetFilesSkipped() int32 {
	if x != nil {
		return x.FilesSkipped
	}
	return 0
}

type ScanLibraryRootsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanLibraryRootsRequest) Reset() {
	*x = ScanLibraryRootsRequest{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanLibraryRootsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanLibraryRootsRequest) ProtoMessage() {}

func (x *ScanLibraryRootsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanLibraryRootsRequest.ProtoReflect.Descriptor instead.
func (*ScanLibraryRootsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{2}
}

type ScanLibraryRootsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesFound    int32                  `protobuf:"varint,1,opt,name=files_found,json=filesFound,proto3" json:"files_found,omitempty"`
	FilesImported int32                  `protobuf:"varint,2,opt,name=files_imported,json=filesImported,proto3" json:"files_imported,omitempty"`
	FilesSkipped  int32                  `protobuf:"varint,3,opt,name=files_skipped,json=filesSkipped,proto3" json:"files_skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanLibraryRootsResponse) Reset() {
	*x = ScanLibraryRootsResponse{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanLibraryRootsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanLibraryRootsResponse) ProtoMessage() {}

func (x *ScanLibraryRootsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanLibraryRootsResponse.ProtoReflect.Descriptor instead.
func (*ScanLibraryRootsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *ScanLibraryRootsResponse) GetFilesFound() int32 {
	if x != nil {
		return x.FilesFound
	}
	return 0
}

func (x *ScanLibraryRootsResponse) GetFilesImported() int32 {
	if x != nil {
		return x.FilesImported
	}
	return 0
}

func (x *ScanLibraryRootsResponse) GetFilesSkipped() int32 {
	if x != nil {
		return x.FilesSkipped
	}
	return 0
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{4}
}

type GetStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalImported  int32                  `protobuf:"varint,1,opt,name=total_imported,json=totalImported,proto3" json:"total_imported,omitempty"`
	WatchDirs      int32                  `protobuf:"varint,2,opt,name=watch_dirs,json=watchDirs,proto3" json:"watch_dirs,omitempty"`
	LastScanAt     int64                  `protobuf:"varint,3,opt,name=last_scan_at,json=lastScanAt,proto3" json:"last_scan_at,omitempty"`
	LastScanStatus string                 `protobuf:"bytes,4,opt,name=last_scan_status,json=lastScanStatus,proto3" json:"last_scan_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatsResponse) GetTotalImported() int32 {
	if x != nil {
		return x.TotalImported
	}
	return 0
}

func (x *GetStatsResponse) GetWatchDirs() int32 {
	if x != nil {
		return x.WatchDirs
	}
	return 0
}

func (x *GetStatsResponse) GetLastScanAt() int64 {
	if x != nil {
		return x.LastScanAt
	}
	return 0
}

func (x *GetStatsResponse) GetLastScanStatus() string {
	if x != nil {
		return x.LastScanStatus
	}
	return ""
}

type AddWatchDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`       // "movie", "tv", "both"
	LibraryPath   string                 `protobuf:"bytes,3,opt,name=library_path,json=libraryPath,proto3" json:"library_path,omitempty"` // where to move organized files
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWatchDirRequest) Reset() {
	*x = AddWatchDirRequest{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWatchDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWatchDirRequest) ProtoMessage() {}

func (x *AddWatchDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWatchDirRequest.ProtoReflect.Descriptor instead.
func (*AddWatchDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{6}
}

func (x *AddWatchDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddWatchDirRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *AddWatchDirRequest) GetLibraryPath() string {
	if x != nil {
		return x.LibraryPath
	}
	return ""
}

type AddWatchDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWatchDirResponse) Reset() {
	*x = AddWatchDirResponse{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWatchDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWatchDirResponse) ProtoMessage() {}

func (x *AddWatchDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWatchDirResponse.ProtoReflect.Descriptor instead.
func (*AddWatchDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{7}
}

func (x *AddWatchDirResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveWatchDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWatchDirRequest) Reset() {
	*x = RemoveWatchDirRequest{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWatchDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWatchDirRequest) ProtoMessage() {}

func (x *RemoveWatchDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWatchDirRequest.ProtoReflect.Descriptor instead.
func (*RemoveWatchDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveWatchDirRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveWatchDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWatchDirResponse) Reset() {
	*x = RemoveWatchDirResponse{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWatchDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWatchDirResponse) ProtoMessage() {}

func (x *RemoveWatchDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWatchDirResponse.ProtoReflect.Descriptor instead.
func (*RemoveWatchDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{9}
}

type ListWatchDirsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWatchDirsRequest) Reset() {
	*x = ListWatchDirsRequest{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWatchDirsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchDirsRequest) ProtoMessage() {}

func (x *ListWatchDirsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchDirsRequest.ProtoReflect.Descriptor instead.
func (*ListWatchDirsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{10}
}

type ListWatchDirsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dirs          []*WatchDir            `protobuf:"bytes,1,rep,name=dirs,proto3" json:"dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWatchDirsResponse) Reset() {
	*x = ListWatchDirsResponse{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWatchDirsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchDirsResponse) ProtoMessage() {}

func (x *ListWatchDirsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchDirsResponse.ProtoReflect.Descriptor instead.
func (*ListWatchDirsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{11}
}

func (x *ListWatchDirsResponse) GetDirs() []*WatchDir {
	if x != nil {
		return x.Dirs
	}
	return nil
}

type WatchDir struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	LibraryPath   string                 `protobuf:"bytes,4,opt,name=library_path,json=libraryPath,proto3" json:"library_path,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDir) Reset() {
	*x = WatchDir{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDir) ProtoMessage() {}

func (x *WatchDir) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDir.ProtoReflect.Descriptor instead.
func (*WatchDir) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{12}
}

func (x *WatchDir) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WatchDir) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WatchDir) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *WatchDir) GetLibraryPath() string {
	if x != nil {
		return x.LibraryPath
	}
	return ""
}

func (x *WatchDir) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WatchDir) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListImportedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImportedRequest) Reset() {
	*x = ListImportedRequest{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImportedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImportedRequest) ProtoMessage() {}

func (x *ListImportedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImportedRequest.ProtoReflect.Descriptor instead.
func (*ListImportedRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{13}
}

func (x *ListImportedRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListImportedRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListImportedRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type ListImportedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*ImportedFile        `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImportedResponse) Reset() {
	*x = ListImportedResponse{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImportedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImportedResponse) ProtoMessage() {}

func (x *ListImportedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImportedResponse.ProtoReflect.Descriptor instead.
func (*ListImportedResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{14}
}

func (x *ListImportedResponse) GetFiles() []*ImportedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListImportedResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListImportedResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListImportedResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ImportedFile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalPath    string                 `protobuf:"bytes,2,opt,name=original_path,json=originalPath,proto3" json:"original_path,omitempty"`
	DestinationPath string                 `protobuf:"bytes,3,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	FileName        string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MediaType       string                 `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Title           string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Year            int32                  `protobuf:"varint,7,opt,name=year,proto3" json:"year,omitempty"`
	SeasonNumber    int32                  `protobuf:"varint,8,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeNumber   int32                  `protobuf:"varint,9,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	Quality         string                 `protobuf:"bytes,10,opt,name=quality,proto3" json:"quality,omitempty"`
	TmdbId          int32                  `protobuf:"varint,11,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	ImportedAt      string                 `protobuf:"bytes,12,opt,name=imported_at,json=importedAt,proto3" json:"imported_at,omitempty"`
	Status          string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImportedFile) Reset() {
	*x = ImportedFile{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportedFile) ProtoMessage() {}

func (x *ImportedFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportedFile.ProtoReflect.Descriptor instead.
func (*ImportedFile) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{15}
}

func (x *ImportedFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImportedFile) GetOriginalPath() string {
	if x != nil {
		return x.OriginalPath
	}
	return ""
}

func (x *ImportedFile) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *ImportedFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ImportedFile) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ImportedFile) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImportedFile) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ImportedFile) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *ImportedFile) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *ImportedFile) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *ImportedFile) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *ImportedFile) GetImportedAt() string {
	if x != nil {
		return x.ImportedAt
	}
	return ""
}

func (x *ImportedFile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ImportPathRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Optional acquisition hints from media-automation (wanted item / queue row).
	TmdbId        int32  `protobuf:"varint,2,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title         string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	SeasonNumber  int32  `protobuf:"varint,5,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeNumber int32  `protobuf:"varint,6,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportPathRequest) Reset() {
	*x = ImportPathRequest{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportPathRequest) ProtoMessage() {}

func (x *ImportPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportPathRequest.ProtoReflect.Descriptor instead.
func (*ImportPathRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{16}
}

func (x *ImportPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ImportPathRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *ImportPathRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImportPathRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ImportPathRequest) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *ImportPathRequest) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

type ImportPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesFound    int32                  `protobuf:"varint,1,opt,name=files_found,json=filesFound,proto3" json:"files_found,omitempty"`
	FilesImported int32                  `protobuf:"varint,2,opt,name=files_imported,json=filesImported,proto3" json:"files_imported,omitempty"`
	FilesSkipped  int32                  `protobuf:"varint,3,opt,name=files_skipped,json=filesSkipped,proto3" json:"files_skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportPathResponse) Reset() {
	*x = ImportPathResponse{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportPathResponse) ProtoMessage() {}

func (x *ImportPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportPathResponse.ProtoReflect.Descriptor instead.
func (*ImportPathResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{17}
}

func (x *ImportPathResponse) GetFilesFound() int32 {
	if x != nil {
		return x.FilesFound
	}
	return 0
}

func (x *ImportPathResponse) GetFilesImported() int32 {
	if x != nil {
		return x.FilesImported
	}
	return 0
}

func (x *ImportPathResponse) GetFilesSkipped() int32 {
	if x != nil {
		return x.FilesSkipped
	}
	return 0
}

type ListImportCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImportCandidatesRequest) Reset() {
	*x = ListImportCandidatesRequest{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImportCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImportCandidatesRequest) ProtoMessage() {}

func (x *ListImportCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImportCandidatesRequest.ProtoReflect.Descriptor instead.
func (*ListImportCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{18}
}

func (x *ListImportCandidatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ImportCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	WatchDirId    string                 `protobuf:"bytes,4,opt,name=watch_dir_id,json=watchDirId,proto3" json:"watch_dir_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportCandidate) Reset() {
	*x = ImportCandidate{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCandidate) ProtoMessage() {}

func (x *ImportCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCandidate.ProtoReflect.Descriptor instead.
func (*ImportCandidate) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{19}
}

func (x *ImportCandidate) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ImportCandidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImportCandidate) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImportCandidate) GetWatchDirId() string {
	if x != nil {
		return x.WatchDirId
	}
	return ""
}

type ListImportCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*ImportCandidate     `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImportCandidatesResponse) Reset() {
	*x = ListImportCandidatesResponse{}
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImportCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImportCandidatesResponse) ProtoMessage() {}

func (x *ListImportCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scannerv1_scanner_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImportCandidatesResponse.ProtoReflect.Descriptor instead.
func (*ListImportCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_scannerv1_scanner_proto_rawDescGZIP(), []int{20}
}

func (x *ListImportCandidatesResponse) GetCandidates() []*ImportCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

var File_proto_scannerv1_scanner_proto protoreflect.FileDescriptor

const file_proto_scannerv1_scanner_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/scannerv1/scanner.proto\x12\x12muxcore.scanner.v1\"\r\n" +
	"\vScanRequest\"{\n" +
	"\fScanResponse\x12\x1f\n" +
	"\vfiles_found\x18\x01 \x01(\x05R\n" +
	"filesFound\x12%\n" +
	"\x0efiles_imported\x18\x02 \x01(\x05R\rfilesImported\x12#\n" +
	"\rfiles_skipped\x18\x03 \x01(\x05R\ffilesSkipped\"\x19\n" +
	"\x17ScanLibraryRootsRequest\"\x87\x01\n" +
	"\x18ScanLibraryRootsResponse\x12\x1f\n" +
	"\vfiles_found\x18\x01 \x01(\x05R\n" +
	"filesFound\x12%\n" +
	"\x0efiles_imported\x18\x02 \x01(\x05R\rfilesImported\x12#\n" +
	"\rfiles_skipped\x18\x03 \x01(\x05R\ffilesSkipped\"\x11\n" +
	"\x0fGetStatsRequest\"\xa4\x01\n" +
	"\x10GetStatsResponse\x12%\n" +
	"\x0etotal_imported\x18\x01 \x01(\x05R\rtotalImported\x12\x1d\n" +
	"\n" +
	"watch_dirs\x18\x02 \x01(\x05R\twatchDirs\x12 \n" +
	"\flast_scan_at\x18\x03 \x01(\x03R\n" +
	"lastScanAt\x12(\n" +
	"\x10last_scan_status\x18\x04 \x01(\tR\x0elastScanStatus\"j\n" +
	"\x12AddWatchDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12!\n" +
	"\flibrary_path\x18\x03 \x01(\tR\vlibraryPath\"%\n" +
	"\x13AddWatchDirResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15RemoveWatchDirRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16RemoveWatchDirResponse\"\x16\n" +
	"\x14ListWatchDirsRequest\"I\n" +
	"\x15ListWatchDirsResponse\x120\n" +
	"\x04dirs\x18\x01 \x03(\v2\x1c.muxcore.scanner.v1.WatchDirR\x04dirs\"\xa9\x01\n" +
	"\bWatchDir\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12!\n" +
	"\flibrary_path\x18\x04 \x01(\tR\vlibraryPath\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"e\n" +
	"\x13ListImportedRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\"\x95\x01\n" +
	"\x14ListImportedResponse\x126\n" +
	"\x05files\x18\x01 \x03(\v2 .muxcore.scanner.v1.ImportedFileR\x05files\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x8c\x03\n" +
	"\fImportedFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\roriginal_path\x18\x02 \x01(\tR\foriginalPath\x12)\n" +
	"\x10destination_path\x18\x03 \x01(\tR\x0fdestinationPath\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"media_type\x18\x05 \x01(\tR\tmediaType\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\a \x01(\x05R\x04year\x12#\n" +
	"\rseason_number\x18\b \x01(\x05R\fseasonNumber\x12%\n" +
	"\x0eepisode_number\x18\t \x01(\x05R\repisodeNumber\x12\x18\n" +
	"\aquality\x18\n" +
	" \x01(\tR\aquality\x12\x17\n" +
	"\atmdb_id\x18\v \x01(\x05R\x06tmdbId\x12\x1f\n" +
	"\vimported_at\x18\f \x01(\tR\n" +
	"importedAt\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\"\xb6\x01\n" +
	"\x11ImportPathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x17\n" +
	"\atmdb_id\x18\x02 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12#\n" +
	"\rseason_number\x18\x05 \x01(\x05R\fseasonNumber\x12%\n" +
	"\x0eepisode_number\x18\x06 \x01(\x05R\repisodeNumber\"\x81\x01\n" +
	"\x12ImportPathResponse\x12\x1f\n" +
	"\vfiles_found\x18\x01 \x01(\x05R\n" +
	"filesFound\x12%\n" +
	"\x0efiles_imported\x18\x02 \x01(\x05R\rfilesImported\x12#\n" +
	"\rfiles_skipped\x18\x03 \x01(\x05R\ffilesSkipped\"3\n" +
	"\x1bListImportCandidatesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"o\n" +
	"\x0fImportCandidate\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12 \n" +
	"\fwatch_dir_id\x18\x04 \x01(\tR\n" +
	"watchDirId\"c\n" +
	"\x1cListImportCandidatesResponse\x12C\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2#.muxcore.scanner.v1.ImportCandidateR\n" +
	"candidates2\x8b\a\n" +
	"\x0eScannerService\x12I\n" +
	"\x04Scan\x12\x1f.muxcore.scanner.v1.ScanRequest\x1a .muxcore.scanner.v1.ScanResponse\x12m\n" +
	"\x10ScanLibraryRoots\x12+.muxcore.scanner.v1.ScanLibraryRootsRequest\x1a,.muxcore.scanner.v1.ScanLibraryRootsResponse\x12U\n" +
	"\bGetStats\x12#.muxcore.scanner.v1.GetStatsRequest\x1a$.muxcore.scanner.v1.GetStatsResponse\x12^\n" +
	"\vAddWatchDir\x12&.muxcore.scanner.v1.AddWatchDirRequest\x1a'.muxcore.scanner.v1.AddWatchDirResponse\x12g\n" +
	"\x0eRemoveWatchDir\x12).muxcore.scanner.v1.RemoveWatchDirRequest\x1a*.muxcore.scanner.v1.RemoveWatchDirResponse\x12d\n" +
	"\rListWatchDirs\x12(.muxcore.scanner.v1.ListWatchDirsRequest\x1a).muxcore.scanner.v1.ListWatchDirsResponse\x12a\n" +
	"\fListImported\x12'.muxcore.scanner.v1.ListImportedRequest\x1a(.muxcore.scanner.v1.ListImportedResponse\x12[\n" +
	"\n" +
	"ImportPath\x12%.muxcore.scanner.v1.ImportPathRequest\x1a&.muxcore.scanner.v1.ImportPathResponse\x12y\n" +
	"\x14ListImportCandidates\x12/.muxcore.scanner.v1.ListImportCandidatesRequest\x1a0.muxcore.scanner.v1.ListImportCandidatesResponseBBZ@github.com/Muxcore-Media/contracts-scanner/muxcore/scanner/v1;scannerv1b\x06proto3"

var (
	file_proto_scannerv1_scanner_proto_rawDescOnce sync.Once
	file_proto_scannerv1_scanner_proto_rawDescData []byte
)

func file_proto_scannerv1_scanner_proto_rawDescGZIP() []byte {
	file_proto_scannerv1_scanner_proto_rawDescOnce.Do(func() {
		file_proto_scannerv1_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scannerv1_scanner_proto_rawDesc), len(file_proto_scannerv1_scanner_proto_rawDesc)))
	})
	return file_proto_scannerv1_scanner_proto_rawDescData
}

var file_proto_scannerv1_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_scannerv1_scanner_proto_goTypes = []any{
	(*ScanRequest)(nil),                  // 0: muxcore.scanner.v1.ScanRequest
	(*ScanResponse)(nil),                 // 1: muxcore.scanner.v1.ScanResponse
	(*ScanLibraryRootsRequest)(nil),      // 2: muxcore.scanner.v1.ScanLibraryRootsRequest
	(*ScanLibraryRootsResponse)(nil),     // 3: muxcore.scanner.v1.ScanLibraryRootsResponse
	(*GetStatsRequest)(nil),              // 4: muxcore.scanner.v1.GetStatsRequest
	(*GetStatsResponse)(nil),             // 5: muxcore.scanner.v1.GetStatsResponse
	(*AddWatchDirRequest)(nil),           // 6: muxcore.scanner.v1.AddWatchDirRequest
	(*AddWatchDirResponse)(nil),          // 7: muxcore.scanner.v1.AddWatchDirResponse
	(*RemoveWatchDirRequest)(nil),        // 8: muxcore.scanner.v1.RemoveWatchDirRequest
	(*RemoveWatchDirResponse)(nil),       // 9: muxcore.scanner.v1.RemoveWatchDirResponse
	(*ListWatchDirsRequest)(nil),         // 10: muxcore.scanner.v1.ListWatchDirsRequest
	(*ListWatchDirsResponse)(nil),        // 11: muxcore.scanner.v1.ListWatchDirsResponse
	(*WatchDir)(nil),                     // 12: muxcore.scanner.v1.WatchDir
	(*ListImportedRequest)(nil),          // 13: muxcore.scanner.v1.ListImportedRequest
	(*ListImportedResponse)(nil),         // 14: muxcore.scanner.v1.ListImportedResponse
	(*ImportedFile)(nil),                 // 15: muxcore.scanner.v1.ImportedFile
	(*ImportPathRequest)(nil),            // 16: muxcore.scanner.v1.ImportPathRequest
	(*ImportPathResponse)(nil),           // 17: muxcore.scanner.v1.ImportPathResponse
	(*ListImportCandidatesRequest)(nil),  // 18: muxcore.scanner.v1.ListImportCandidatesRequest
	(*ImportCandidate)(nil),              // 19: muxcore.scanner.v1.ImportCandidate
	(*ListImportCandidatesResponse)(nil), // 20: muxcore.scanner.v1.ListImportCandidatesResponse
}
var file_proto_scannerv1_scanner_proto_depIdxs = []int32{
	12, // 0: muxcore.scanner.v1.ListWatchDirsResponse.dirs:type_name -> muxcore.scanner.v1.WatchDir
	15, // 1: muxcore.scanner.v1.ListImportedResponse.files:type_name -> muxcore.scanner.v1.ImportedFile
	19, // 2: muxcore.scanner.v1.ListImportCandidatesResponse.candidates:type_name -> muxcore.scanner.v1.ImportCandidate
	0,  // 3: muxcore.scanner.v1.ScannerService.Scan:input_type -> muxcore.scanner.v1.ScanRequest
	2,  // 4: muxcore.scanner.v1.ScannerService.ScanLibraryRoots:input_type -> muxcore.scanner.v1.ScanLibraryRootsRequest
	4,  // 5: muxcore.scanner.v1.ScannerService.GetStats:input_type -> muxcore.scanner.v1.GetStatsRequest
	6,  // 6: muxcore.scanner.v1.ScannerService.AddWatchDir:input_type -> muxcore.scanner.v1.AddWatchDirRequest
	8,  // 7: muxcore.scanner.v1.ScannerService.RemoveWatchDir:input_type -> muxcore.scanner.v1.RemoveWatchDirRequest
	10, // 8: muxcore.scanner.v1.ScannerService.ListWatchDirs:input_type -> muxcore.scanner.v1.ListWatchDirsRequest
	13, // 9: muxcore.scanner.v1.ScannerService.ListImported:input_type -> muxcore.scanner.v1.ListImportedRequest
	16, // 10: muxcore.scanner.v1.ScannerService.ImportPath:input_type -> muxcore.scanner.v1.ImportPathRequest
	18, // 11: muxcore.scanner.v1.ScannerService.ListImportCandidates:input_type -> muxcore.scanner.v1.ListImportCandidatesRequest
	1,  // 12: muxcore.scanner.v1.ScannerService.Scan:output_type -> muxcore.scanner.v1.ScanResponse
	3,  // 13: muxcore.scanner.v1.ScannerService.ScanLibraryRoots:output_type -> muxcore.scanner.v1.ScanLibraryRootsResponse
	5,  // 14: muxcore.scanner.v1.ScannerService.GetStats:output_type -> muxcore.scanner.v1.GetStatsResponse
	7,  // 15: muxcore.scanner.v1.ScannerService.AddWatchDir:output_type -> muxcore.scanner.v1.AddWatchDirResponse
	9,  // 16: muxcore.scanner.v1.ScannerService.RemoveWatchDir:output_type -> muxcore.scanner.v1.RemoveWatchDirResponse
	11, // 17: muxcore.scanner.v1.ScannerService.ListWatchDirs:output_type -> muxcore.scanner.v1.ListWatchDirsResponse
	14, // 18: muxcore.scanner.v1.ScannerService.ListImported:output_type -> muxcore.scanner.v1.ListImportedResponse
	17, // 19: muxcore.scanner.v1.ScannerService.ImportPath:output_type -> muxcore.scanner.v1.ImportPathResponse
	20, // 20: muxcore.scanner.v1.ScannerService.ListImportCandidates:output_type -> muxcore.scanner.v1.ListImportCandidatesResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_scannerv1_scanner_proto_init() }
func file_proto_scannerv1_scanner_proto_init() {
	if File_proto_scannerv1_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scannerv1_scanner_proto_rawDesc), len(file_proto_scannerv1_scanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scannerv1_scanner_proto_goTypes,
		DependencyIndexes: file_proto_scannerv1_scanner_proto_depIdxs,
		MessageInfos:      file_proto_scannerv1_scanner_proto_msgTypes,
	}.Build()
	File_proto_scannerv1_scanner_proto = out.File
	file_proto_scannerv1_scanner_proto_goTypes = nil
	file_proto_scannerv1_scanner_proto_depIdxs = nil
}
