// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/scannerv1/scanner.proto

package scannerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScannerService_Scan_FullMethodName                 = "/muxcore.scanner.v1.ScannerService/Scan"
	ScannerService_ScanLibraryRoots_FullMethodName     = "/muxcore.scanner.v1.ScannerService/ScanLibraryRoots"
	ScannerService_GetStats_FullMethodName             = "/muxcore.scanner.v1.ScannerService/GetStats"
	ScannerService_AddWatchDir_FullMethodName          = "/muxcore.scanner.v1.ScannerService/AddWatchDir"
	ScannerService_RemoveWatchDir_FullMethodName       = "/muxcore.scanner.v1.ScannerService/RemoveWatchDir"
	ScannerService_ListWatchDirs_FullMethodName        = "/muxcore.scanner.v1.ScannerService/ListWatchDirs"
	ScannerService_ListImported_FullMethodName         = "/muxcore.scanner.v1.ScannerService/ListImported"
	ScannerService_ImportPath_FullMethodName           = "/muxcore.scanner.v1.ScannerService/ImportPath"
	ScannerService_ListImportCandidates_FullMethodName = "/muxcore.scanner.v1.ScannerService/ListImportCandidates"
)

// ScannerServiceClient is the client API for ScannerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScannerServiceClient interface {
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	ScanLibraryRoots(ctx context.Context, in *ScanLibraryRootsRequest, opts ...grpc.CallOption) (*ScanLibraryRootsResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	AddWatchDir(ctx context.Context, in *AddWatchDirRequest, opts ...grpc.CallOption) (*AddWatchDirResponse, error)
	RemoveWatchDir(ctx context.Context, in *RemoveWatchDirRequest, opts ...grpc.CallOption) (*RemoveWatchDirResponse, error)
	ListWatchDirs(ctx context.Context, in *ListWatchDirsRequest, opts ...grpc.CallOption) (*ListWatchDirsResponse, error)
	ListImported(ctx context.Context, in *ListImportedRequest, opts ...grpc.CallOption) (*ListImportedResponse, error)
	ImportPath(ctx context.Context, in *ImportPathRequest, opts ...grpc.CallOption) (*ImportPathResponse, error)
	ListImportCandidates(ctx context.Context, in *ListImportCandidatesRequest, opts ...grpc.CallOption) (*ListImportCandidatesResponse, error)
}

type scannerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScannerServiceClient(cc grpc.ClientConnInterface) ScannerServiceClient {
	return &scannerServiceClient{cc}
}

func (c *scannerServiceClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, ScannerService_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerServiceClient) ScanLibraryRoots(ctx context.Context, in *ScanLibraryRootsRequest, opts ...grpc.CallOption) (*ScanLibraryRootsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanLibraryRootsResponse)
	err := c.cc.Invoke(ctx, ScannerService_ScanLibraryRoots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, ScannerService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerServiceClient) AddWatchDir(ctx context.Context, in *AddWatchDirRequest, opts ...grpc.CallOption) (*AddWatchDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddWatchDirResponse)
	err := c.cc.Invoke(ctx, ScannerService_AddWatchDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerServiceClient) RemoveWatchDir(ctx context.Context, in *RemoveWatchDirRequest, opts ...grpc.CallOption) (*RemoveWatchDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveWatchDirResponse)
	err := c.cc.Invoke(ctx, ScannerService_RemoveWatchDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerServiceClient) ListWatchDirs(ctx context.Context, in *ListWatchDirsRequest, opts ...grpc.CallOption) (*ListWatchDirsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchDirsResponse)
	err := c.cc.Invoke(ctx, ScannerService_ListWatchDirs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerServiceClient) ListImported(ctx context.Context, in *ListImportedRequest, opts ...grpc.CallOption) (*ListImportedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImportedResponse)
	err := c.cc.Invoke(ctx, ScannerService_ListImported_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerServiceClient) ImportPath(ctx context.Context, in *ImportPathRequest, opts ...grpc.CallOption) (*ImportPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportPathResponse)
	err := c.cc.Invoke(ctx, ScannerService_ImportPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerServiceClient) ListImportCandidates(ctx context.Context, in *ListImportCandidatesRequest, opts ...grpc.CallOption) (*ListImportCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImportCandidatesResponse)
	err := c.cc.Invoke(ctx, ScannerService_ListImportCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScannerServiceServer is the server API for ScannerService service.
// All implementations must embed UnimplementedScannerServiceServer
// for forward compatibility.
type ScannerServiceServer interface {
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	ScanLibraryRoots(context.Context, *ScanLibraryRootsRequest) (*ScanLibraryRootsResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	AddWatchDir(context.Context, *AddWatchDirRequest) (*AddWatchDirResponse, error)
	RemoveWatchDir(context.Context, *RemoveWatchDirRequest) (*RemoveWatchDirResponse, error)
	ListWatchDirs(context.Context, *ListWatchDirsRequest) (*ListWatchDirsResponse, error)
	ListImported(context.Context, *ListImportedRequest) (*ListImportedResponse, error)
	ImportPath(context.Context, *ImportPathRequest) (*ImportPathResponse, error)
	ListImportCandidates(context.Context, *ListImportCandidatesRequest) (*ListImportCandidatesResponse, error)
	mustEmbedUnimplementedScannerServiceServer()
}

// UnimplementedScannerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScannerServiceServer struct{}

func (UnimplementedScannerServiceServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedScannerServiceServer) ScanLibraryRoots(context.Context, *ScanLibraryRootsRequest) (*ScanLibraryRootsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanLibraryRoots not implemented")
}
func (UnimplementedScannerServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedScannerServiceServer) AddWatchDir(context.Context, *AddWatchDirRequest) (*AddWatchDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWatchDir not implemented")
}
func (UnimplementedScannerServiceServer) RemoveWatchDir(context.Context, *RemoveWatchDirRequest) (*RemoveWatchDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveWatchDir not implemented")
}
func (UnimplementedScannerServiceServer) ListWatchDirs(context.Context, *ListWatchDirsRequest) (*ListWatchDirsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWatchDirs not implemented")
}
func (UnimplementedScannerServiceServer) ListImported(context.Context, *ListImportedRequest) (*ListImportedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImported not implemented")
}
func (UnimplementedScannerServiceServer) ImportPath(context.Context, *ImportPathRequest) (*ImportPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportPath not implemented")
}
func (UnimplementedScannerServiceServer) ListImportCandidates(context.Context, *ListImportCandidatesRequest) (*ListImportCandidatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImportCandidates not implemented")
}
func (UnimplementedScannerServiceServer) mustEmbedUnimplementedScannerServiceServer() {}
func (UnimplementedScannerServiceServer) testEmbeddedByValue()                        {}

// UnsafeScannerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScannerServiceServer will
// result in compilation errors.
type UnsafeScannerServiceServer interface {
	mustEmbedUnimplementedScannerServiceServer()
}

func RegisterScannerServiceServer(s grpc.ServiceRegistrar, srv ScannerServiceServer) {
	// If the following call pancis, it indicates UnimplementedScannerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScannerService_ServiceDesc, srv)
}

func _ScannerService_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServiceServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerService_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServiceServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerService_ScanLibraryRoots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanLibraryRootsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServiceServer).ScanLibraryRoots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerService_ScanLibraryRoots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServiceServer).ScanLibraryRoots(ctx, req.(*ScanLibraryRootsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerService_AddWatchDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWatchDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServiceServer).AddWatchDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerService_AddWatchDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServiceServer).AddWatchDir(ctx, req.(*AddWatchDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerService_RemoveWatchDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWatchDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServiceServer).RemoveWatchDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerService_RemoveWatchDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServiceServer).RemoveWatchDir(ctx, req.(*RemoveWatchDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerService_ListWatchDirs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchDirsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServiceServer).ListWatchDirs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerService_ListWatchDirs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServiceServer).ListWatchDirs(ctx, req.(*ListWatchDirsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerService_ListImported_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImportedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServiceServer).ListImported(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerService_ListImported_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServiceServer).ListImported(ctx, req.(*ListImportedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerService_ImportPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServiceServer).ImportPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerService_ImportPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServiceServer).ImportPath(ctx, req.(*ImportPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerService_ListImportCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImportCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServiceServer).ListImportCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerService_ListImportCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServiceServer).ListImportCandidates(ctx, req.(*ListImportCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScannerService_ServiceDesc is the grpc.ServiceDesc for ScannerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScannerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.scanner.v1.ScannerService",
	HandlerType: (*ScannerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scan",
			Handler:    _ScannerService_Scan_Handler,
		},
		{
			MethodName: "ScanLibraryRoots",
			Handler:    _ScannerService_ScanLibraryRoots_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _ScannerService_GetStats_Handler,
		},
		{
			MethodName: "AddWatchDir",
			Handler:    _ScannerService_AddWatchDir_Handler,
		},
		{
			MethodName: "RemoveWatchDir",
			Handler:    _ScannerService_RemoveWatchDir_Handler,
		},
		{
			MethodName: "ListWatchDirs",
			Handler:    _ScannerService_ListWatchDirs_Handler,
		},
		{
			MethodName: "ListImported",
			Handler:    _ScannerService_ListImported_Handler,
		},
		{
			MethodName: "ImportPath",
			Handler:    _ScannerService_ImportPath_Handler,
		},
		{
			MethodName: "ListImportCandidates",
			Handler:    _ScannerService_ListImportCandidates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scannerv1/scanner.proto",
}
